/**
 * generated by Xtext 2.17.1
 */
package fr.n7.simplepdl.txt.ide;

import fr.n7.simplepdl.txt.ide.AbstractPDLIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class PDLIdeModule extends AbstractPDLIdeModule {
}
