/**
 * @file tpl_app_config.c
 *
 * @section desc File description
 *
 * OS data structure generated from application test
 * Automatically generated by goil on Mon Dec  2 12:25:57 2019
 * from root OIL file nxtSegway.oil
 *
 * @section copyright Copyright
 *
 * Trampoline OS
 *
 * Trampoline is copyright (c) IRCCyN 2005-2007
 * Trampoline is protected by the French intellectual property law.
 *
 * This software is distributed under the Lesser GNU Public Licence
 *
 * @section infos File informations
 *
 * $Date$
 * $Rev$
 * $Author$
 * $URL$
 */

#include "tpl_app_config.h"

#include "tpl_os_internal_types.h"
#include "tpl_machine.h"
#include "tpl_os_it.h"
#include "tpl_os_it_kernel.h"
#include "tpl_os_alarm_kernel.h"
#include "tpl_os_alarm.h"
#include "tpl_os_rez_kernel.h"
#include "tpl_os_rez.h"
#include "tpl_os_event_kernel.h"
#include "tpl_os_event.h"
#include "tpl_os_action.h"
#include "tpl_os_kernel.h"
#include "tpl_os_definitions.h"


#define API_START_SEC_CONST_UNSPECIFIED
#include "tpl_memmap.h"

/*=============================================================================
 * Declaration of processes IDs
 */

/* Task affichage identifier */
#define affichage_id 0
CONST(TaskType, AUTOMATIC) affichage = affichage_id;

/* Task pendule identifier */
#define pendule_id 1
CONST(TaskType, AUTOMATIC) pendule = pendule_id;

/* ISR isr_button_left identifier */
#define isr_button_left_id 2
/* ISR isr_button_right identifier */
#define isr_button_right_id 3
/* ISR isr_button_start identifier */
#define isr_button_start_id 4
/* ISR isr_button_stop identifier */
#define isr_button_stop_id 5
/*=============================================================================
 * Declaration of Alarm IDs
 */

/* Alarm alarm_affichage identifier */
#define alarm_affichage_id 0
CONST(AlarmType, AUTOMATIC) alarm_affichage = alarm_affichage_id;

/* Alarm alarm_pendule identifier */
#define alarm_pendule_id 1
CONST(AlarmType, AUTOMATIC) alarm_pendule = alarm_pendule_id;

#define API_STOP_SEC_CONST_UNSPECIFIED
#include "tpl_memmap.h"

#define OS_START_SEC_CONST_UNSPECIFIED
#include "tpl_memmap.h"
CONSTP2VAR(tpl_resource, AUTOMATIC, OS_APPL_DATA)
tpl_resource_table[RESOURCE_COUNT] = {
  &res_sched_rez_desc  
};
#define OS_STOP_SEC_CONST_UNSPECIFIED
#include "tpl_memmap.h"


/*=============================================================================
 * Definition and initialization of Counters related defines and structures
 */
/*-----------------------------------------------------------------------------
 * Counter SystemCounter descriptor
 */

#define API_START_SEC_CONST_UNSPECIFIED
#include "tpl_memmap.h"

CONST(tpl_tick, OS_CONST) OSTICKSPERBASE = 1;
CONST(tpl_tick, OS_CONST) OSMAXALLOWEDVALUE = 32767;
CONST(tpl_tick, OS_CONST) OSMINCYCLE = 1;

#define API_STOP_SEC_CONST_UNSPECIFIED
#include "tpl_memmap.h"

#define OS_START_SEC_VAR_UNSPECIFIED
#include "tpl_memmap.h"

VAR(tpl_counter, OS_VAR) SystemCounter_counter_desc = {
  /* ticks per base       */  1,
  /* max allowed value    */  32767,
  /* minimum cycle        */  1,
  /* current tick         */  0,
  /* current date         */  0,
#if WITH_OSAPPLICATION == YES
    /* OS Application id    */  
#endif
    /* first alarm          */  NULL_PTR,
    /* next alarm to raise  */  NULL_PTR
};

#define OS_STOP_SEC_VAR_UNSPECIFIED
#include "tpl_memmap.h"

/*-----------------------------------------------------------------------------
 * Counter compteur descriptor
 */

#define API_START_SEC_CONST_UNSPECIFIED
#include "tpl_memmap.h"

CONST(tpl_tick, OS_CONST) OSTICKSPERBASE_compteur = 1;
CONST(tpl_tick, OS_CONST) OSMAXALLOWEDVALUE_compteur = 5000000;
CONST(tpl_tick, OS_CONST) OSMINCYCLE_compteur = 1;

#define API_STOP_SEC_CONST_UNSPECIFIED
#include "tpl_memmap.h"

#define OS_START_SEC_VAR_UNSPECIFIED
#include "tpl_memmap.h"

VAR(tpl_counter, OS_VAR) compteur_counter_desc = {
  /* ticks per base       */  1,
  /* max allowed value    */  5000000,
  /* minimum cycle        */  1,
  /* current tick         */  0,
  /* current date         */  0,
#if WITH_OSAPPLICATION == YES
    /* OS Application id    */  
#endif
    /* first alarm          */  NULL_PTR,
    /* next alarm to raise  */  NULL_PTR
};

#define OS_STOP_SEC_VAR_UNSPECIFIED
#include "tpl_memmap.h"

#include "tpl_os_kernel.h"          /* tpl_schedule */
#include "tpl_os_timeobj_kernel.h"  /* tpl_counter_tick */
#include "tpl_machine_interface.h"  /* tpl_switch_context_from_it */
#include "AT91SAM7.h" /* AT91C_AIC_ISCR */

#define OS_START_SEC_VAR_8BIT
#include "tpl_memmap.h"
VAR(u8, OS_VAR) check_buttons_period = 0;
#define OS_STOP_SEC_VAR_8BIT
#include "tpl_memmap.h"

#define OS_START_SEC_CODE
#include "tpl_memmap.h"

FUNC(void, OS_CODE) tpl_tick_it_timer1()
{
  tpl_status  need_rescheduling = NO_SPECIAL_CODE;

  need_rescheduling |= tpl_counter_tick(&compteur_counter_desc);

  
  check_buttons_period++;
  if (check_buttons_period == 10)
  {
    /* Call check_buttons_status() (via interrupts)
     * which will check if buttons are pressed or not.
     */
     *AT91C_AIC_ISCR = (1 << AT91C_PERIPHERAL_ID_IRQ0);
     check_buttons_period = 0;
  }

  if (need_rescheduling == NEED_RESCHEDULING)
  {
    tpl_schedule_from_running();
#if WITH_SYSTEM_CALL == NO
    if (tpl_kern.need_switch != NO_NEED_SWITCH) {
      tpl_switch_context_from_it(
        &(tpl_kern.s_old->context),
        &(tpl_kern.s_running->context)
      );
    }
#endif
  }
}

#define OS_STOP_SEC_CODE
#include "tpl_memmap.h"


/*=============================================================================
 * Definition and initialization of Task related defines and structures
 */
/*-----------------------------------------------------------------------------
 * Task affichage descriptor
 */
#define APP_Task_affichage_START_SEC_CODE
#include "tpl_memmap.h"
/*
 * Task affichage function prototype
 */
FUNC(void, OS_APPL_CODE) affichage_function(void);
#define APP_Task_affichage_STOP_SEC_CODE
#include "tpl_memmap.h"

/*-----------------------------------------------------------------------------
 * Target specific structures
 */
/*
 * Task affichage stack
 */
#define APP_Task_affichage_START_SEC_STACK
#include "tpl_memmap.h"
VAR(tpl_stack_word, OS_APPL_DATA) affichage_stack_zone[512/sizeof(tpl_stack_word)];
#define APP_Task_affichage_STOP_SEC_STACK
#include "tpl_memmap.h"

#define affichage_STACK {affichage_stack_zone, 512}

/*
 * Task affichage context
 */
#define OS_START_SEC_VAR_NOINIT_32BIT
#include "tpl_memmap.h"
VAR(arm_context, OS_VAR) affichage_int_context;

#define affichage_CONTEXT &affichage_int_context

#define OS_STOP_SEC_VAR_NOINIT_32BIT
#include "tpl_memmap.h"





#if WITH_AUTOSAR_TIMING_PROTECTION == YES
#define OS_START_SEC_VAR_UNSPECIFIED
#include "tpl_memmap.h"

#define OS_STOP_SEC_VAR_UNSPECIFIED
#include "tpl_memmap.h"
#endif


#define OS_START_SEC_CONST_UNSPECIFIED
#include "tpl_memmap.h"


/*
 * Static descriptor of task affichage
 */
CONST(tpl_proc_static, OS_CONST) affichage_task_stat_desc = {
  /* context                  */  affichage_CONTEXT,
  /* stack                    */  affichage_STACK,
  /* entry point (function)   */  affichage_function,
  /* internal ressource       */  NULL,
  /* task id                  */  affichage_id,
#if WITH_OSAPPLICATION == YES
  /* OS application id        */  
#endif
  /* task base priority       */  1,
  /* max activation count     */  1,
  /* task type                */  TASK_BASIC,
#if WITH_AUTOSAR_TIMING_PROTECTION == YES
  /* pointer to the timing
     protection descriptor    */  $TIMING_PROT_REF$
#endif
};

#define OS_STOP_SEC_CONST_UNSPECIFIED
#include "tpl_memmap.h"


#define OS_START_SEC_VAR_UNSPECIFIED
#include "tpl_memmap.h"
/*
 * Dynamic descriptor of task affichage
 */
VAR(tpl_proc, OS_VAR) affichage_task_desc = {
  /* resources                      */  NULL,
#if WITH_MEMORY_PROTECTION == YES
  /* if > 0 the process is trusted  */  0,    
#endif /* WITH_MEMORY_PROTECTION */
  /* activate count                 */  0,
  /* task priority                  */  1,
  /* task state                     */  SUSPENDED
#if WITH_AUTOSAR_TIMING_PROTECTION == YES
    /* activation allowed             */  ,TRUE
#endif
};

#define OS_STOP_SEC_VAR_UNSPECIFIED
#include "tpl_memmap.h"

/*-----------------------------------------------------------------------------
 * Task pendule descriptor
 */
#define APP_Task_pendule_START_SEC_CODE
#include "tpl_memmap.h"
/*
 * Task pendule function prototype
 */
FUNC(void, OS_APPL_CODE) pendule_function(void);
#define APP_Task_pendule_STOP_SEC_CODE
#include "tpl_memmap.h"

/*-----------------------------------------------------------------------------
 * Target specific structures
 */
/*
 * Task pendule stack
 */
#define APP_Task_pendule_START_SEC_STACK
#include "tpl_memmap.h"
VAR(tpl_stack_word, OS_APPL_DATA) pendule_stack_zone[512/sizeof(tpl_stack_word)];
#define APP_Task_pendule_STOP_SEC_STACK
#include "tpl_memmap.h"

#define pendule_STACK {pendule_stack_zone, 512}

/*
 * Task pendule context
 */
#define OS_START_SEC_VAR_NOINIT_32BIT
#include "tpl_memmap.h"
VAR(arm_context, OS_VAR) pendule_int_context;

#define pendule_CONTEXT &pendule_int_context

#define OS_STOP_SEC_VAR_NOINIT_32BIT
#include "tpl_memmap.h"





#if WITH_AUTOSAR_TIMING_PROTECTION == YES
#define OS_START_SEC_VAR_UNSPECIFIED
#include "tpl_memmap.h"

#define OS_STOP_SEC_VAR_UNSPECIFIED
#include "tpl_memmap.h"
#endif


#define OS_START_SEC_CONST_UNSPECIFIED
#include "tpl_memmap.h"


/*
 * Static descriptor of task pendule
 */
CONST(tpl_proc_static, OS_CONST) pendule_task_stat_desc = {
  /* context                  */  pendule_CONTEXT,
  /* stack                    */  pendule_STACK,
  /* entry point (function)   */  pendule_function,
  /* internal ressource       */  NULL,
  /* task id                  */  pendule_id,
#if WITH_OSAPPLICATION == YES
  /* OS application id        */  
#endif
  /* task base priority       */  2,
  /* max activation count     */  1,
  /* task type                */  TASK_BASIC,
#if WITH_AUTOSAR_TIMING_PROTECTION == YES
  /* pointer to the timing
     protection descriptor    */  $TIMING_PROT_REF$
#endif
};

#define OS_STOP_SEC_CONST_UNSPECIFIED
#include "tpl_memmap.h"


#define OS_START_SEC_VAR_UNSPECIFIED
#include "tpl_memmap.h"
/*
 * Dynamic descriptor of task pendule
 */
VAR(tpl_proc, OS_VAR) pendule_task_desc = {
  /* resources                      */  NULL,
#if WITH_MEMORY_PROTECTION == YES
  /* if > 0 the process is trusted  */  0,    
#endif /* WITH_MEMORY_PROTECTION */
  /* activate count                 */  0,
  /* task priority                  */  2,
  /* task state                     */  SUSPENDED
#if WITH_AUTOSAR_TIMING_PROTECTION == YES
    /* activation allowed             */  ,TRUE
#endif
};

#define OS_STOP_SEC_VAR_UNSPECIFIED
#include "tpl_memmap.h"


/*=============================================================================
 * Definition and initialization of ISR2 related defines and structures
 */
/*-----------------------------------------------------------------------------
 * ISR isr_button_left descriptor
 */
#define APP_ISR_isr_button_left_START_SEC_CODE
#include "tpl_memmap.h"
/*
 * ISR isr_button_left function prototype
 */
FUNC(void, OS_APPL_CODE) isr_button_left_function(void);
#define APP_ISR_isr_button_left_STOP_SEC_CODE
#include "tpl_memmap.h"

/*-----------------------------------------------------------------------------
 * Target specific structures
 */
/*
 * ISR isr_button_left stack
 */
#define APP_ISR_isr_button_left_START_SEC_STACK
#include "tpl_memmap.h"
VAR(tpl_stack_word, OS_APPL_DATA) isr_button_left_stack_zone[500/sizeof(tpl_stack_word)];
#define APP_ISR_isr_button_left_STOP_SEC_STACK
#include "tpl_memmap.h"

#define isr_button_left_STACK {isr_button_left_stack_zone, 500}

/*
 * ISR isr_button_left context
 */
#define OS_START_SEC_VAR_NOINIT_32BIT
#include "tpl_memmap.h"
VAR(arm_context, OS_VAR) isr_button_left_int_context;

#define isr_button_left_CONTEXT &isr_button_left_int_context

#define OS_STOP_SEC_VAR_NOINIT_32BIT
#include "tpl_memmap.h"





#if WITH_AUTOSAR_TIMING_PROTECTION == YES
#define OS_START_SEC_VAR_UNSPECIFIED
#include "tpl_memmap.h"

#define OS_STOP_SEC_VAR_UNSPECIFIED
#include "tpl_memmap.h"
#endif

#define OS_START_SEC_CONST_UNSPECIFIED
#include "tpl_memmap.h"


/*
 * Static descriptor of ISR isr_button_left
 */
CONST(tpl_proc_static, OS_CONST) isr_button_left_isr_stat_desc = {
  /* context                  */  isr_button_left_CONTEXT,
  /* stack                    */  isr_button_left_STACK,
  /* entry point (function)   */  isr_button_left_function,
  /* internal ressource       */  NULL,
  /* ISR id                   */  isr_button_left_id,
#if WITH_OSAPPLICATION == YES
  /* OS application id        */  
#endif
  /* task base priority       */  3,
  /* max activation count     */  1,
  /* task type                */  IS_ROUTINE,
#if WITH_AUTOSAR_TIMING_PROTECTION == YES
  /* pointer to the timing
     protection descriptor    */  $TIMING_PROT_REF$
#endif
};

tpl_isr_static isr_button_left_isr_helper = {
  /* helper */ NULL,
  /* next */   NULL,
  /* id */     isr_button_left_id
};

#define OS_STOP_SEC_CONST_UNSPECIFIED
#include "tpl_memmap.h"


#define OS_START_SEC_VAR_UNSPECIFIED
#include "tpl_memmap.h"
/*
 * Dynamic descriptor of ISR isr_button_left
 */
VAR(tpl_proc, OS_VAR) isr_button_left_isr_desc = {
  /* resources                      */  NULL,
#if WITH_MEMORY_PROTECTION == YES
  /* if > 0 the process is trusted  */  0,    
#endif /* WITH_MEMORY_PROTECTION */
  /* activate count                 */  0,
  /* ISR priority                   */  3,
  /* ISR state                      */  SUSPENDED,
#if WITH_AUTOSAR_TIMING_PROTECTION == YES
  /* activation allowed             */  ,TRUE
#endif
};
#define OS_STOP_SEC_VAR_UNSPECIFIED
#include "tpl_memmap.h"

/*-----------------------------------------------------------------------------
 * ISR isr_button_right descriptor
 */
#define APP_ISR_isr_button_right_START_SEC_CODE
#include "tpl_memmap.h"
/*
 * ISR isr_button_right function prototype
 */
FUNC(void, OS_APPL_CODE) isr_button_right_function(void);
#define APP_ISR_isr_button_right_STOP_SEC_CODE
#include "tpl_memmap.h"

/*-----------------------------------------------------------------------------
 * Target specific structures
 */
/*
 * ISR isr_button_right stack
 */
#define APP_ISR_isr_button_right_START_SEC_STACK
#include "tpl_memmap.h"
VAR(tpl_stack_word, OS_APPL_DATA) isr_button_right_stack_zone[500/sizeof(tpl_stack_word)];
#define APP_ISR_isr_button_right_STOP_SEC_STACK
#include "tpl_memmap.h"

#define isr_button_right_STACK {isr_button_right_stack_zone, 500}

/*
 * ISR isr_button_right context
 */
#define OS_START_SEC_VAR_NOINIT_32BIT
#include "tpl_memmap.h"
VAR(arm_context, OS_VAR) isr_button_right_int_context;

#define isr_button_right_CONTEXT &isr_button_right_int_context

#define OS_STOP_SEC_VAR_NOINIT_32BIT
#include "tpl_memmap.h"





#if WITH_AUTOSAR_TIMING_PROTECTION == YES
#define OS_START_SEC_VAR_UNSPECIFIED
#include "tpl_memmap.h"

#define OS_STOP_SEC_VAR_UNSPECIFIED
#include "tpl_memmap.h"
#endif

#define OS_START_SEC_CONST_UNSPECIFIED
#include "tpl_memmap.h"


/*
 * Static descriptor of ISR isr_button_right
 */
CONST(tpl_proc_static, OS_CONST) isr_button_right_isr_stat_desc = {
  /* context                  */  isr_button_right_CONTEXT,
  /* stack                    */  isr_button_right_STACK,
  /* entry point (function)   */  isr_button_right_function,
  /* internal ressource       */  NULL,
  /* ISR id                   */  isr_button_right_id,
#if WITH_OSAPPLICATION == YES
  /* OS application id        */  
#endif
  /* task base priority       */  3,
  /* max activation count     */  1,
  /* task type                */  IS_ROUTINE,
#if WITH_AUTOSAR_TIMING_PROTECTION == YES
  /* pointer to the timing
     protection descriptor    */  $TIMING_PROT_REF$
#endif
};

tpl_isr_static isr_button_right_isr_helper = {
  /* helper */ NULL,
  /* next */   NULL,
  /* id */     isr_button_right_id
};

#define OS_STOP_SEC_CONST_UNSPECIFIED
#include "tpl_memmap.h"


#define OS_START_SEC_VAR_UNSPECIFIED
#include "tpl_memmap.h"
/*
 * Dynamic descriptor of ISR isr_button_right
 */
VAR(tpl_proc, OS_VAR) isr_button_right_isr_desc = {
  /* resources                      */  NULL,
#if WITH_MEMORY_PROTECTION == YES
  /* if > 0 the process is trusted  */  0,    
#endif /* WITH_MEMORY_PROTECTION */
  /* activate count                 */  0,
  /* ISR priority                   */  3,
  /* ISR state                      */  SUSPENDED,
#if WITH_AUTOSAR_TIMING_PROTECTION == YES
  /* activation allowed             */  ,TRUE
#endif
};
#define OS_STOP_SEC_VAR_UNSPECIFIED
#include "tpl_memmap.h"

/*-----------------------------------------------------------------------------
 * ISR isr_button_start descriptor
 */
#define APP_ISR_isr_button_start_START_SEC_CODE
#include "tpl_memmap.h"
/*
 * ISR isr_button_start function prototype
 */
FUNC(void, OS_APPL_CODE) isr_button_start_function(void);
#define APP_ISR_isr_button_start_STOP_SEC_CODE
#include "tpl_memmap.h"

/*-----------------------------------------------------------------------------
 * Target specific structures
 */
/*
 * ISR isr_button_start stack
 */
#define APP_ISR_isr_button_start_START_SEC_STACK
#include "tpl_memmap.h"
VAR(tpl_stack_word, OS_APPL_DATA) isr_button_start_stack_zone[500/sizeof(tpl_stack_word)];
#define APP_ISR_isr_button_start_STOP_SEC_STACK
#include "tpl_memmap.h"

#define isr_button_start_STACK {isr_button_start_stack_zone, 500}

/*
 * ISR isr_button_start context
 */
#define OS_START_SEC_VAR_NOINIT_32BIT
#include "tpl_memmap.h"
VAR(arm_context, OS_VAR) isr_button_start_int_context;

#define isr_button_start_CONTEXT &isr_button_start_int_context

#define OS_STOP_SEC_VAR_NOINIT_32BIT
#include "tpl_memmap.h"





#if WITH_AUTOSAR_TIMING_PROTECTION == YES
#define OS_START_SEC_VAR_UNSPECIFIED
#include "tpl_memmap.h"

#define OS_STOP_SEC_VAR_UNSPECIFIED
#include "tpl_memmap.h"
#endif

#define OS_START_SEC_CONST_UNSPECIFIED
#include "tpl_memmap.h"


/*
 * Static descriptor of ISR isr_button_start
 */
CONST(tpl_proc_static, OS_CONST) isr_button_start_isr_stat_desc = {
  /* context                  */  isr_button_start_CONTEXT,
  /* stack                    */  isr_button_start_STACK,
  /* entry point (function)   */  isr_button_start_function,
  /* internal ressource       */  NULL,
  /* ISR id                   */  isr_button_start_id,
#if WITH_OSAPPLICATION == YES
  /* OS application id        */  
#endif
  /* task base priority       */  3,
  /* max activation count     */  1,
  /* task type                */  IS_ROUTINE,
#if WITH_AUTOSAR_TIMING_PROTECTION == YES
  /* pointer to the timing
     protection descriptor    */  $TIMING_PROT_REF$
#endif
};

tpl_isr_static isr_button_start_isr_helper = {
  /* helper */ NULL,
  /* next */   NULL,
  /* id */     isr_button_start_id
};

#define OS_STOP_SEC_CONST_UNSPECIFIED
#include "tpl_memmap.h"


#define OS_START_SEC_VAR_UNSPECIFIED
#include "tpl_memmap.h"
/*
 * Dynamic descriptor of ISR isr_button_start
 */
VAR(tpl_proc, OS_VAR) isr_button_start_isr_desc = {
  /* resources                      */  NULL,
#if WITH_MEMORY_PROTECTION == YES
  /* if > 0 the process is trusted  */  0,    
#endif /* WITH_MEMORY_PROTECTION */
  /* activate count                 */  0,
  /* ISR priority                   */  3,
  /* ISR state                      */  SUSPENDED,
#if WITH_AUTOSAR_TIMING_PROTECTION == YES
  /* activation allowed             */  ,TRUE
#endif
};
#define OS_STOP_SEC_VAR_UNSPECIFIED
#include "tpl_memmap.h"

/*-----------------------------------------------------------------------------
 * ISR isr_button_stop descriptor
 */
#define APP_ISR_isr_button_stop_START_SEC_CODE
#include "tpl_memmap.h"
/*
 * ISR isr_button_stop function prototype
 */
FUNC(void, OS_APPL_CODE) isr_button_stop_function(void);
#define APP_ISR_isr_button_stop_STOP_SEC_CODE
#include "tpl_memmap.h"

/*-----------------------------------------------------------------------------
 * Target specific structures
 */
/*
 * ISR isr_button_stop stack
 */
#define APP_ISR_isr_button_stop_START_SEC_STACK
#include "tpl_memmap.h"
VAR(tpl_stack_word, OS_APPL_DATA) isr_button_stop_stack_zone[500/sizeof(tpl_stack_word)];
#define APP_ISR_isr_button_stop_STOP_SEC_STACK
#include "tpl_memmap.h"

#define isr_button_stop_STACK {isr_button_stop_stack_zone, 500}

/*
 * ISR isr_button_stop context
 */
#define OS_START_SEC_VAR_NOINIT_32BIT
#include "tpl_memmap.h"
VAR(arm_context, OS_VAR) isr_button_stop_int_context;

#define isr_button_stop_CONTEXT &isr_button_stop_int_context

#define OS_STOP_SEC_VAR_NOINIT_32BIT
#include "tpl_memmap.h"





#if WITH_AUTOSAR_TIMING_PROTECTION == YES
#define OS_START_SEC_VAR_UNSPECIFIED
#include "tpl_memmap.h"

#define OS_STOP_SEC_VAR_UNSPECIFIED
#include "tpl_memmap.h"
#endif

#define OS_START_SEC_CONST_UNSPECIFIED
#include "tpl_memmap.h"


/*
 * Static descriptor of ISR isr_button_stop
 */
CONST(tpl_proc_static, OS_CONST) isr_button_stop_isr_stat_desc = {
  /* context                  */  isr_button_stop_CONTEXT,
  /* stack                    */  isr_button_stop_STACK,
  /* entry point (function)   */  isr_button_stop_function,
  /* internal ressource       */  NULL,
  /* ISR id                   */  isr_button_stop_id,
#if WITH_OSAPPLICATION == YES
  /* OS application id        */  
#endif
  /* task base priority       */  3,
  /* max activation count     */  1,
  /* task type                */  IS_ROUTINE,
#if WITH_AUTOSAR_TIMING_PROTECTION == YES
  /* pointer to the timing
     protection descriptor    */  $TIMING_PROT_REF$
#endif
};

tpl_isr_static isr_button_stop_isr_helper = {
  /* helper */ NULL,
  /* next */   NULL,
  /* id */     isr_button_stop_id
};

#define OS_STOP_SEC_CONST_UNSPECIFIED
#include "tpl_memmap.h"


#define OS_START_SEC_VAR_UNSPECIFIED
#include "tpl_memmap.h"
/*
 * Dynamic descriptor of ISR isr_button_stop
 */
VAR(tpl_proc, OS_VAR) isr_button_stop_isr_desc = {
  /* resources                      */  NULL,
#if WITH_MEMORY_PROTECTION == YES
  /* if > 0 the process is trusted  */  0,    
#endif /* WITH_MEMORY_PROTECTION */
  /* activate count                 */  0,
  /* ISR priority                   */  3,
  /* ISR state                      */  SUSPENDED,
#if WITH_AUTOSAR_TIMING_PROTECTION == YES
  /* activation allowed             */  ,TRUE
#endif
};
#define OS_STOP_SEC_VAR_UNSPECIFIED
#include "tpl_memmap.h"

#include "tpl_machine.h"


/* Interrupt functions */

#define OS_START_SEC_CODE
#include "tpl_memmap.h"

FUNC(void, OS_CODE) tpl_interrupt_source_1()
{

  tpl_tick_it_timer1();

  systick_isr_C_function(); 

}

FUNC(void, OS_CODE) tpl_interrupt_source_2()
{

  nxt_motor_isr_C_function(); 

}

FUNC(void, OS_CODE) tpl_interrupt_source_5()
{

  spi_isr_C_function(); 

}

FUNC(void, OS_CODE) tpl_interrupt_source_7()
{

  bt_isr_C_function(); 

}

FUNC(void, OS_CODE) tpl_interrupt_source_9()
{

  twi_isr_C_function(); 

}

FUNC(void, OS_CODE) tpl_interrupt_source_10()
{

  systick_low_priority_C_function(); 

}

FUNC(void, OS_CODE) tpl_interrupt_source_12()
{

  i2c_timer_isr_C_function(); 

}

FUNC(void, OS_CODE) tpl_interrupt_source_15()
{

  tpl_central_interrupt_handler(4); 

}

FUNC(void, OS_CODE) tpl_interrupt_source_16()
{

  tpl_central_interrupt_handler(2); 

}

FUNC(void, OS_CODE) tpl_interrupt_source_17()
{

  tpl_central_interrupt_handler(3); 

}

FUNC(void, OS_CODE) tpl_interrupt_source_18()
{

  tpl_central_interrupt_handler(5); 

}

FUNC(void, OS_CODE) tpl_interrupt_source_30()
{

  check_buttons_status_function(); 

}

#define OS_STOP_SEC_CODE
#include "tpl_memmap.h"


/* Interrupt table vector */

#define OS_START_SEC_CONST_UNSPECIFIED
#include "tpl_memmap.h"
CONST(tpl_it_vector_entry, OS_CONST) tpl_it_vector[31] = {
  { tpl_null_it, (void *)NULL },
  { tpl_interrupt_source_1, (void *)NULL },
  { tpl_interrupt_source_2, (void *)NULL },
  { tpl_null_it, (void *)NULL },
  { tpl_null_it, (void *)NULL },
  { tpl_interrupt_source_5, (void *)NULL },
  { tpl_null_it, (void *)NULL },
  { tpl_interrupt_source_7, (void *)NULL },
  { tpl_null_it, (void *)NULL },
  { tpl_interrupt_source_9, (void *)NULL },
  { tpl_interrupt_source_10, (void *)NULL },
  { tpl_null_it, (void *)NULL },
  { tpl_interrupt_source_12, (void *)NULL },
  { tpl_null_it, (void *)NULL },
  { tpl_null_it, (void *)NULL },
  { tpl_interrupt_source_15, (void *)NULL },
  { tpl_interrupt_source_16, (void *)NULL },
  { tpl_interrupt_source_17, (void *)NULL },
  { tpl_interrupt_source_18, (void *)NULL },
  { tpl_null_it, (void *)NULL },
  { tpl_null_it, (void *)NULL },
  { tpl_null_it, (void *)NULL },
  { tpl_null_it, (void *)NULL },
  { tpl_null_it, (void *)NULL },
  { tpl_null_it, (void *)NULL },
  { tpl_null_it, (void *)NULL },
  { tpl_null_it, (void *)NULL },
  { tpl_null_it, (void *)NULL },
  { tpl_null_it, (void *)NULL },
  { tpl_null_it, (void *)NULL },
  { tpl_interrupt_source_30, (void *)NULL }
};
#define OS_STOP_SEC_CONST_UNSPECIFIED
#include "tpl_memmap.h"


#define OS_START_SEC_CONST_UNSPECIFIED
#include "tpl_memmap.h"
/*=============================================================================
 * Definition and initialization of process tables (tasks and isrs)
 */
CONSTP2CONST(tpl_proc_static, AUTOMATIC, OS_APPL_DATA)
tpl_stat_proc_table[TASK_COUNT+ISR_COUNT+1] = {
  &affichage_task_stat_desc,
  &pendule_task_stat_desc,
  &isr_button_left_isr_stat_desc,
  &isr_button_right_isr_stat_desc,
  &isr_button_start_isr_stat_desc,
  &isr_button_stop_isr_stat_desc,
  &idle_task_static
};

CONSTP2VAR(tpl_proc, AUTOMATIC, OS_APPL_DATA)
tpl_dyn_proc_table[TASK_COUNT+ISR_COUNT+1] = {
  &affichage_task_desc,
  &pendule_task_desc,
  &isr_button_left_isr_desc,
  &isr_button_right_isr_desc,
  &isr_button_start_isr_desc,
  &isr_button_stop_isr_desc,
  &idle_task
};

CONSTP2CONST(tpl_isr_static, AUTOMATIC, OS_APPL_DATA)
tpl_isr_stat_table[ISR_COUNT] = {
  &isr_button_left_isr_helper,
  &isr_button_right_isr_helper,
  &isr_button_start_isr_helper,
  &isr_button_stop_isr_helper
};

#define OS_STOP_SEC_CONST_UNSPECIFIED
#include "tpl_memmap.h"


/*=============================================================================
 * Definition and initialization of Alarm related structures
 */
/*-----------------------------------------------------------------------------
 * Alarm alarm_affichage descriptor
 *
 * This alarm does the activation of task affichage
 */

#define OS_START_SEC_CONST_UNSPECIFIED
#include "tpl_memmap.h"


CONST(tpl_task_activation_action, OS_CONST) alarm_affichage_action = {
  {
    /* action function  */  tpl_action_activate_task
  },
  /* task id            */  affichage_id
};

#define OS_STOP_SEC_CONST_UNSPECIFIED
#include "tpl_memmap.h"

 
#define OS_START_SEC_CONST_UNSPECIFIED
#include "tpl_memmap.h"

CONST(tpl_alarm_static, OS_CONST) alarm_affichage_static = {
  {
    /* pointer to counter           */  &compteur_counter_desc,
    /* pointer to the expiration    */  tpl_raise_alarm
#if (WITH_TRACE == YES)
    /* id of the alarm for tracing  */  , alarm_affichage_id
#endif
#if WITH_OSAPPLICATION == YES
    /* OS application id            */  , 
#endif
  },
  /* action of the alarm  */  (tpl_action *)&alarm_affichage_action
};

#define OS_STOP_SEC_CONST_UNSPECIFIED
#include "tpl_memmap.h"

#define OS_START_SEC_VAR_UNSPECIFIED
#include "tpl_memmap.h"

VAR(tpl_time_obj, OS_VAR) alarm_affichage_alarm_desc = {
    /* pointer to the static part   */  (tpl_time_obj_static *)&alarm_affichage_static,
    /* next alarm                   */  NULL,
    /* prev alarm                   */  NULL,
    /* cycle                        */  500,
    /* date                         */  1,
    /* State of the alarm           */  ALARM_AUTOSTART
};

#define OS_STOP_SEC_VAR_UNSPECIFIED
#include "tpl_memmap.h"

/*-----------------------------------------------------------------------------
 * Alarm alarm_pendule descriptor
 *
 * This alarm does the activation of task pendule
 */

#define OS_START_SEC_CONST_UNSPECIFIED
#include "tpl_memmap.h"


CONST(tpl_task_activation_action, OS_CONST) alarm_pendule_action = {
  {
    /* action function  */  tpl_action_activate_task
  },
  /* task id            */  pendule_id
};

#define OS_STOP_SEC_CONST_UNSPECIFIED
#include "tpl_memmap.h"

 
#define OS_START_SEC_CONST_UNSPECIFIED
#include "tpl_memmap.h"

CONST(tpl_alarm_static, OS_CONST) alarm_pendule_static = {
  {
    /* pointer to counter           */  &compteur_counter_desc,
    /* pointer to the expiration    */  tpl_raise_alarm
#if (WITH_TRACE == YES)
    /* id of the alarm for tracing  */  , alarm_pendule_id
#endif
#if WITH_OSAPPLICATION == YES
    /* OS application id            */  , 
#endif
  },
  /* action of the alarm  */  (tpl_action *)&alarm_pendule_action
};

#define OS_STOP_SEC_CONST_UNSPECIFIED
#include "tpl_memmap.h"

#define OS_START_SEC_VAR_UNSPECIFIED
#include "tpl_memmap.h"

VAR(tpl_time_obj, OS_VAR) alarm_pendule_alarm_desc = {
    /* pointer to the static part   */  (tpl_time_obj_static *)&alarm_pendule_static,
    /* next alarm                   */  NULL,
    /* prev alarm                   */  NULL,
    /* cycle                        */  4,
    /* date                         */  1,
    /* State of the alarm           */  ALARM_AUTOSTART
};

#define OS_STOP_SEC_VAR_UNSPECIFIED
#include "tpl_memmap.h"


#define OS_START_SEC_CONST_UNSPECIFIED
#include "tpl_memmap.h"
CONSTP2VAR(tpl_time_obj, AUTOMATIC, OS_APPL_DATA)
  tpl_alarm_table[ALARM_COUNT] = {
  &alarm_affichage_alarm_desc,
  &alarm_pendule_alarm_desc
};
#define OS_STOP_SEC_CONST_UNSPECIFIED
#include "tpl_memmap.h"

/*=============================================================================
 * Declaration of flags functions
 */
/* $FLAGSFUNCTIONS$ */


/*=============================================================================
 * Definition and initialization of Ready List structures
 */
#define OS_START_SEC_VAR_UNSPECIFIED
#include "tpl_memmap.h"

VAR(tpl_proc_id, OS_VAR) tpl_priority_0_fifo[1];
VAR(tpl_proc_id, OS_VAR) tpl_priority_1_fifo[1];
VAR(tpl_proc_id, OS_VAR) tpl_priority_2_fifo[2];
VAR(tpl_proc_id, OS_VAR) tpl_priority_3_fifo[12];

VAR(tpl_fifo_state, OS_VAR) tpl_fifo_rw[4] = {
  { 0 , 0 },
  { 0 , 0 },
  { 0 , 0 },
  { 0 , 0 }
};

#define OS_STOP_SEC_VAR_UNSPECIFIED
#include "tpl_memmap.h"

#define OS_START_SEC_CONST_UNSPECIFIED
#include "tpl_memmap.h"

CONST(tpl_priority_level, OS_CONST) tpl_ready_list[4] = {
  { tpl_priority_0_fifo, 1 },
  { tpl_priority_1_fifo, 1 },
  { tpl_priority_2_fifo, 2 },
  { tpl_priority_3_fifo, 12 }
};

#define OS_STOP_SEC_CONST_UNSPECIFIED
#include "tpl_memmap.h"


#define API_START_SEC_CONST_UNSPECIFIED
#include "tpl_memmap.h"
CONSTP2CONST(char, AUTOMATIC, OS_APPL_DATA) proc_name_table[TASK_COUNT + ISR_COUNT] = {
  "affichage",
  "pendule",
  "isr_button_left",
  "isr_button_right",
  "isr_button_start",
  "isr_button_stop"
};
#define API_STOP_SEC_CONST_UNSPECIFIED
#include "tpl_memmap.h"

/* End of file tpl_app_config.c */

