#-------------------------------------------------------
#   Configuration générale de yane
#-------------------------------------------------------
yane :
  verbose: False
  debug: False
  
#-------------------------------------------------------
# Paramètres par défaut d'un réseau
#-------------------------------------------------------
network :
  startup : startup.sh

#-------------------------------------------------------
# Paramètres par défaut d'un hôte
#-------------------------------------------------------
hosts :
  default :
    -
      mode: netns

#-------------------------------------------------------
# Paramètres par défaut d'un netns
#-------------------------------------------------------
netns :
  default:
    -
      files: %n/etc:/
      init: /etc/yane-guest-init %n
      
#-------------------------------------------------------
# Paramètres par défaut d'un docker
#-------------------------------------------------------
docker :
  default:
    -
      image: "debian:latest"
      files: docker/%n:/
