/**
 * generated by Xtext 2.17.1
 */
package fr.n7.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import fr.n7.PDL1RuntimeModule;
import fr.n7.PDL1StandaloneSetup;
import fr.n7.ide.PDL1IdeModule;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class PDL1IdeSetup extends PDL1StandaloneSetup {
  @Override
  public Injector createInjector() {
    PDL1RuntimeModule _pDL1RuntimeModule = new PDL1RuntimeModule();
    PDL1IdeModule _pDL1IdeModule = new PDL1IdeModule();
    return Guice.createInjector(Modules2.mixin(_pDL1RuntimeModule, _pDL1IdeModule));
  }
}
