/**
 * generated by Xtext 2.17.1
 */
package fr.n7.simplepdl.txt.ui.labeling;

import org.eclipse.xtext.ui.label.DefaultDescriptionLabelProvider;

/**
 * Provides labels for IEObjectDescriptions and IResourceDescriptions.
 * 
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#label-provider
 */
@SuppressWarnings("all")
public class PDLDescriptionLabelProvider extends DefaultDescriptionLabelProvider {
}
