/*
 * generated by Xtext 2.17.1
 */
package fr.n7.scoping


/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
class PDL2ScopeProvider extends AbstractPDL2ScopeProvider {

}
