/**
 * generated by Xtext 2.17.1
 */
package fr.n7.simplepdl.txt;

import fr.n7.simplepdl.txt.PDLStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class PDLStandaloneSetup extends PDLStandaloneSetupGenerated {
  public static void doSetup() {
    new PDLStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
