/**
 * generated by Xtext 2.17.1
 */
package fr.n7.pDL3.impl;

import fr.n7.pDL3.PDL3Package;
import fr.n7.pDL3.ProcessElement;
import fr.n7.pDL3.WorkDefinition;
import fr.n7.pDL3.WorkSequence;

import java.util.Collection;

import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Process Element</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link fr.n7.pDL3.impl.ProcessElementImpl#getWorkDefinition <em>Work Definition</em>}</li>
 *   <li>{@link fr.n7.pDL3.impl.ProcessElementImpl#getWorkSequence <em>Work Sequence</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ProcessElementImpl extends MinimalEObjectImpl.Container implements ProcessElement
{
  /**
   * The cached value of the '{@link #getWorkDefinition() <em>Work Definition</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getWorkDefinition()
   * @generated
   * @ordered
   */
  protected EList<WorkDefinition> workDefinition;

  /**
   * The cached value of the '{@link #getWorkSequence() <em>Work Sequence</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getWorkSequence()
   * @generated
   * @ordered
   */
  protected EList<WorkSequence> workSequence;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ProcessElementImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return PDL3Package.Literals.PROCESS_ELEMENT;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<WorkDefinition> getWorkDefinition()
  {
    if (workDefinition == null)
    {
      workDefinition = new EObjectContainmentEList<WorkDefinition>(WorkDefinition.class, this, PDL3Package.PROCESS_ELEMENT__WORK_DEFINITION);
    }
    return workDefinition;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<WorkSequence> getWorkSequence()
  {
    if (workSequence == null)
    {
      workSequence = new EObjectContainmentEList<WorkSequence>(WorkSequence.class, this, PDL3Package.PROCESS_ELEMENT__WORK_SEQUENCE);
    }
    return workSequence;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case PDL3Package.PROCESS_ELEMENT__WORK_DEFINITION:
        return ((InternalEList<?>)getWorkDefinition()).basicRemove(otherEnd, msgs);
      case PDL3Package.PROCESS_ELEMENT__WORK_SEQUENCE:
        return ((InternalEList<?>)getWorkSequence()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case PDL3Package.PROCESS_ELEMENT__WORK_DEFINITION:
        return getWorkDefinition();
      case PDL3Package.PROCESS_ELEMENT__WORK_SEQUENCE:
        return getWorkSequence();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case PDL3Package.PROCESS_ELEMENT__WORK_DEFINITION:
        getWorkDefinition().clear();
        getWorkDefinition().addAll((Collection<? extends WorkDefinition>)newValue);
        return;
      case PDL3Package.PROCESS_ELEMENT__WORK_SEQUENCE:
        getWorkSequence().clear();
        getWorkSequence().addAll((Collection<? extends WorkSequence>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case PDL3Package.PROCESS_ELEMENT__WORK_DEFINITION:
        getWorkDefinition().clear();
        return;
      case PDL3Package.PROCESS_ELEMENT__WORK_SEQUENCE:
        getWorkSequence().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case PDL3Package.PROCESS_ELEMENT__WORK_DEFINITION:
        return workDefinition != null && !workDefinition.isEmpty();
      case PDL3Package.PROCESS_ELEMENT__WORK_SEQUENCE:
        return workSequence != null && !workSequence.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //ProcessElementImpl
