/**
 * generated by Xtext 2.17.1
 */
package fr.n7.pDL2;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Process Element</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see fr.n7.pDL2.PDL2Package#getProcessElement()
 * @model
 * @generated
 */
public interface ProcessElement extends EObject
{
} // ProcessElement
