/**
 * generated by Xtext 2.17.1
 */
package fr.n7.pDL2;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Work Sequence Kind Start</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.n7.pDL2.WorkSequenceKindStart#getStarted2Start <em>Started2 Start</em>}</li>
 *   <li>{@link fr.n7.pDL2.WorkSequenceKindStart#getStarted2Finish <em>Started2 Finish</em>}</li>
 * </ul>
 *
 * @see fr.n7.pDL2.PDL2Package#getWorkSequenceKindStart()
 * @model
 * @generated
 */
public interface WorkSequenceKindStart extends EObject
{
  /**
   * Returns the value of the '<em><b>Started2 Start</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Started2 Start</em>' attribute.
   * @see #setStarted2Start(String)
   * @see fr.n7.pDL2.PDL2Package#getWorkSequenceKindStart_Started2Start()
   * @model
   * @generated
   */
  String getStarted2Start();

  /**
   * Sets the value of the '{@link fr.n7.pDL2.WorkSequenceKindStart#getStarted2Start <em>Started2 Start</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Started2 Start</em>' attribute.
   * @see #getStarted2Start()
   * @generated
   */
  void setStarted2Start(String value);

  /**
   * Returns the value of the '<em><b>Started2 Finish</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Started2 Finish</em>' attribute.
   * @see #setStarted2Finish(String)
   * @see fr.n7.pDL2.PDL2Package#getWorkSequenceKindStart_Started2Finish()
   * @model
   * @generated
   */
  String getStarted2Finish();

  /**
   * Sets the value of the '{@link fr.n7.pDL2.WorkSequenceKindStart#getStarted2Finish <em>Started2 Finish</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Started2 Finish</em>' attribute.
   * @see #getStarted2Finish()
   * @generated
   */
  void setStarted2Finish(String value);

} // WorkSequenceKindStart
