/**
 * generated by Xtext 2.17.1
 */
package fr.n7.simplepdl.txt.ui.contentassist;

import fr.n7.simplepdl.txt.ui.contentassist.AbstractPDLProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class PDLProposalProvider extends AbstractPDLProposalProvider {
}
