/*
 * generated by Xtext 2.17.1
 */
package fr.n7.simplepdl.txt.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class PDLUiModule extends AbstractPDLUiModule {
}
