/*
 * generated by Xtext 2.17.1
 */
package fr.n7.ui.tests;

import com.google.inject.Injector;
import fr.n7.pdl1.ui.internal.Pdl1Activator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class PDL1UiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return Pdl1Activator.getInstance().getInjector("fr.n7.PDL1");
	}

}
