/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package fr.n7.gls.test;

import java.io.*;

// TODO : Ajouter un deuxième paramètre qui permet de logger les erreurs.
// On ne donne que l'interface.  On le test.  On peut ensuite en donner une
// implantation naïve : stocker dans une liste et et afficher à la fin (ou
// afficher au fil de l'eau sur la sortie en erreur)...

public class Somme {

	public int somme(BufferedReader f) throws IOException {
		return somme(f, new ErreursAffichage());
	}

	public int somme(BufferedReader f, Erreurs erreurs) throws IOException {
		int resultat = 0;
		String ligne = null;
		while  ((ligne = f.readLine()) != null) {
			try {
				int valeur = Integer.parseInt(ligne);
				if (valeur >= 0) {
					resultat += valeur;
				} else {
					erreurs.signaler(ligne, "Valeur négative");
				}
			} catch (NumberFormatException e) {
				erreurs.signaler(ligne, "Pas un entier !");
			}
		}
		return resultat;
	}

    public static void main(String[] args) throws Exception {
		if (args.length == 1) {
			BufferedReader br = new BufferedReader(new FileReader(args[0]));
			System.out.println(new Somme().somme(br));
		} else {
			System.out.println("Un nom de fichier attendu sur la ligne de commande !");
			System.exit(1);
		}
    }

}

