#!/bin/bash

# Set address on eth0
ip link set dev eth0 up
ip addr add 31.5.254.66/26 dev eth0

# Set address on eth1
ip link set dev eth1 up
ip addr add 31.5.254.129/26 dev eth1

# Static routing
#echo 1 > /proc/sys/net/ipv4/ip_forward
#ip route add 31.5.254.0/26 via 31.5.254.65
#ip route add 192.168.111.0/25 via 31.5.254.65
#ip route add 31.5.254.192/26 via 31.5.254.130

# Dynamic routing
service quagga start
sleep 1
