#!/bin/bash

# Set address on eth0
ip link set dev eth0 up
ip addr add 31.5.254.2/26 dev eth0

# Set address on eth1
ip link set dev eth1 up
ip addr add 31.5.254.65/26 dev eth1

# Static routing
#echo 1 > /proc/sys/net/ipv4/ip_forward
#ip route add 192.168.111.0/26 via 31.5.254.1
#ip route add 31.5.254.128/26 via 31.5.254.66
#ip route add 31.5.254.192/26 via 31.5.254.66

# Dynamic routing
service quagga start
sleep 1
