/**
 * generated by Xtext 2.17.1
 */
package fr.n7;

import fr.n7.PDL2StandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class PDL2StandaloneSetup extends PDL2StandaloneSetupGenerated {
  public static void doSetup() {
    new PDL2StandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
