/*
 * generated by Xtext 2.17.1
 */
package fr.n7


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class PDL3StandaloneSetup extends PDL3StandaloneSetupGenerated {

	def static void doSetup() {
		new PDL3StandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
