(*                           Module Chaines                                   *)

(******************************************************************************)
(*                                                                            *)
(*      fonction de décomposition pour les chaînes de caractères              *)
(*                                                                            *)
(*   signature : decompose_chaine : string -> char list = <fun>               *)
(*                                                                            *)
(*   paramètre(s) : une chaîne de caractères                                  *)
(*   résultat     : la liste des caractères composant la chaîne paramètre     *)
(*                                                                            *)
(******************************************************************************)
val decompose_chaine : string -> char list 

(******************************************************************************)
(*                                                                            *)
(*      fonction de recomposition pour les chaînes de caractères              *)
(*                                                                            *)
(*   signature : recompose_chaine : char list -> string = <fun>               *)
(*                                                                            *)
(*   paramètre(s) : une liste de caractères                                   *)
(*   résultat     : la chaîne des caractères composant la liste paramètre     *)
(*                                                                            *)
(******************************************************************************)
val recompose_chaine : char list -> string

(******************************************************************************)
(*                                                                            *)
(*      fonction de lecture d'une chaîne                                      *)
(*                                                                            *)
(*   signature : lit_chaine : unit -> string = <fun>                          *)
(*                                                                            *)
(*   paramètre(s) : aucun                                                     *)
(*   résultat     : une chaîne                                                *)
(*                                                                            *)
(******************************************************************************)
val lit_chaine : unit -> string

(******************************************************************************)
(*                                                                            *)
(*      procédure d'affichage d'une chaîne                                    *)
(*                                                                            *)
(*   signature : affiche_chaine : string -> unit = <fun>                      *)
(*                                                                            *)
(*   paramètre(s) : une chaîne                                                *)
(*   résultat     : aucun                                                     *)
(*                                                                            *)
(******************************************************************************)
val affiche_chaine : string -> unit
