/**
 * generated by Xtext 2.17.1
 */
package fr.n7.simplepdl.txt.scoping;

import fr.n7.simplepdl.txt.scoping.AbstractPDLScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class PDLScopeProvider extends AbstractPDLScopeProvider {
}
