/*
 * generated by Xtext 2.17.1
 */
package fr.n7.simplepdl.txt.ide

import com.google.inject.Guice
import fr.n7.simplepdl.txt.PDLRuntimeModule
import fr.n7.simplepdl.txt.PDLStandaloneSetup
import org.eclipse.xtext.util.Modules2

/**
 * Initialization support for running Xtext languages as language servers.
 */
class PDLIdeSetup extends PDLStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new PDLRuntimeModule, new PDLIdeModule))
	}
	
}
