/*
 * generated by Xtext 2.17.1
 */
package fr.n7


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class PDL2RuntimeModule extends AbstractPDL2RuntimeModule {
}
