/**
 * generated by Xtext 2.17.1
 */
package fr.n7.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import fr.n7.PDL2RuntimeModule;
import fr.n7.PDL2StandaloneSetup;
import fr.n7.ide.PDL2IdeModule;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class PDL2IdeSetup extends PDL2StandaloneSetup {
  @Override
  public Injector createInjector() {
    PDL2RuntimeModule _pDL2RuntimeModule = new PDL2RuntimeModule();
    PDL2IdeModule _pDL2IdeModule = new PDL2IdeModule();
    return Guice.createInjector(Modules2.mixin(_pDL2RuntimeModule, _pDL2IdeModule));
  }
}
