/*
 * generated by Xtext 2.17.1
 */
package fr.n7.ide

import com.google.inject.Guice
import fr.n7.PDL2RuntimeModule
import fr.n7.PDL2StandaloneSetup
import org.eclipse.xtext.util.Modules2

/**
 * Initialization support for running Xtext languages as language servers.
 */
class PDL2IdeSetup extends PDL2StandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new PDL2RuntimeModule, new PDL2IdeModule))
	}
	
}
